### ISSUE TITLE
Inclusion fichier d'en-tête

### ISSUE THREAD

**Issue by sebmavro** [Ebatsin/reva-stereo#2]
Inclure soil.h comme SOIL/soil.h
Fichiers concernés : 
- include/texture2D.hpp
- src/main.cpp

**Comment by Ebatsin** [comment]
Sur linux, le chemin est SOIL/SOIL.h
Le nom du fichier est t'il vraiment en minuscule sur mac ?

**Comment by sebmavro** [comment]
C'est bien en majuscule soit : SOIL/SOIL.h
Ce qui me "posait problème" c'est que il y avait uniquement SOIL.h et pas SOIL/SOIL.h
Ca roule comme ça !
