### ISSUE TITLE
MacOSX : Echec de la création du contexte GL

### ISSUE THREAD

**Issue by sebmavro** [Ebatsin/reva-stereo#3]
Le contexte GL n'est pas créé, l'application quitte au lancement.

Fichier concerné : src/main.cpp ligne 36
-> 	Window win = Window::Builder(3, 3, true)

Sur portable, chipset intel ...
-> 	Window win = Window::Builder(2, 1, false)
permet le lancement de l'application

**Comment by sebmavro** [comment]
macOS Sierra 10.2.6
Chipset : Intel Iris Plus Graphics 650

Ce n'est pas directement lié à la version du système et au chipset.
Pour faire simple, peu importe la carte, c'est du OpenGL 2.1 qui est supporté généralement sur Mac.

**Comment by Ebatsin** [comment]
Il semblerait qu'il faille spécifier le mode de compatibilité pour que ça marche sur MacOS. J'ai activé le hint à la création de la fenêtre. Merci de tester et m'indiquer si un contexte core profile 3.3 arrive à être créé.

**Comment by sebmavro** [comment]
Nickel :-) !
OpenGL version : 4.1 INTEL-10.25.17
